//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int LessonId { get; set; }
        public int ScheduleId { get; set; }
        public System.DateTime Date { get; set; }
        public string LessonDescribe { get; set; }
        public string H_W { get; set; }
    
        public virtual Schedule Schedule { get; set; }
    }
}
