//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectToTeacher
    {
        public int TeacherId { get; set; }
        public int SubjectId { get; set; }
        public decimal PriceForLesson { get; set; }
        public int LessonLength { get; set; }
        public string GradesRange { get; set; }
    
        public virtual Teacher Teacher { get; set; }
    }
}
