USE [master]
GO

/****** Object:  Database [RacheliandDini]    Script Date: 13/07/2020 14:32:22 ******/
CREATE DATABASE [RacheliandDini]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RacheliandDini', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\RacheliandDini.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RacheliandDini_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\RacheliandDini_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RacheliandDini].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RacheliandDini] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RacheliandDini] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RacheliandDini] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RacheliandDini] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RacheliandDini] SET ARITHABORT OFF 
GO

ALTER DATABASE [RacheliandDini] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RacheliandDini] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RacheliandDini] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RacheliandDini] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RacheliandDini] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RacheliandDini] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RacheliandDini] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RacheliandDini] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RacheliandDini] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RacheliandDini] SET  ENABLE_BROKER 
GO

ALTER DATABASE [RacheliandDini] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RacheliandDini] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RacheliandDini] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RacheliandDini] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RacheliandDini] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RacheliandDini] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RacheliandDini] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RacheliandDini] SET RECOVERY FULL 
GO

ALTER DATABASE [RacheliandDini] SET  MULTI_USER 
GO

ALTER DATABASE [RacheliandDini] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RacheliandDini] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RacheliandDini] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RacheliandDini] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RacheliandDini] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RacheliandDini] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RacheliandDini] SET  READ_WRITE 
GO


